{{ range $environment, $values := .Values.appEnvironments }}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: logging
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  description: "Project for logging components"
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  sourceRepos:
    - https://fluent.github.io/helm-charts
    - {{ $values.repoUrl }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging-master
  namespace: argocd
spec:
  destination:
    namespace: logging
    server: https://kubernetes.default.svc
  project: logging
  source:
    path: k8s/logging
    repoURL: {{ $values.repoUrl }}
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
{{- with $values }}
      values: |- {{ toYaml . | nindent 8 }}
{{- end }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
{{ end }}