apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: argocd
spec:
  destination:
    namespace: logging
    server: https://kubernetes.default.svc
  project: devops
  source:
    repoURL: https://fluent.github.io/helm-charts
    chart: fluent-bit
    targetRevision: latest
    helm:
      values: |
        serviceAccount:
          create: true
          name: fluentbit
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.awsAccountNumber }}:role/eks-fluentbit-role

        input:
          tail:
            enabled: true
            path: /var/log/containers/*.log
            parser: docker

        output:
          s3:
            enabled: true
            bucket: first-order-application-logs
            region: us-east-1
            compression: gzip
            total_file_size: 5M
            upload_timeout: 5s
            store_dir: /var/log/fluentbit
            s3_key_format: /fluent-bit-logs/%Y/%m/%d/%H/%M/%S-${HOSTNAME}.json.gz
